using Microsoft.CodeAnalysis;

namespace ReflectionIT.PropertyThrowGenerator;

public interface ICsFileBuilder : IDisposable {
    ICsFileBuilder AddPreprocessorDirectives();
    ICsFileBuilder AddAutoGeneratedHeader(string by);
    ICsFileBuilder AddStaticUsing(string usingStatement);
    ICsFileBuilder AddUsing(string usingStatement);
    ICsFileBuilder AddFileScopedNamespace(INamespaceSymbol namespaceSymbol, bool condition = true);
    ICsFileBuilder AddNamespace(string? namespaceName, bool condition);
    ICsFileBuilder AddNamespace(INamespaceSymbol containingNamespace);
    ICsFileBuilder AddCommentLine(string line);
    ICsFileBuilder AddXmlCommentLines(params ReadOnlySpan<string> lines);
    ICsFileBuilder AddEmptyLine(bool condition = true);
    ICsFileBuilder AddStatements(params ReadOnlySpan<string> lines);
    ICsFileBuilder AddStatementsIf(bool condition, params ReadOnlySpan<string> lines);
    ICsFileBuilder AddStatementAndStartBlock(string line);
    ICsFileBuilder AddIfBlock(string condition, params ReadOnlySpan<string> lines);
    ICsFileBuilder EndBlock();
    ICsFileBuilder EndNamespace();

    ICsFileBuilder AddGeneratedAttributes(string generatorName, bool useFullyQualifiedTypeNames = true, bool includeNonUserCodeAttributes = true);

    ICsFileBuilder AddText(string text);

    ICsFileBuilder AddPartialType(ITypeSymbol typeSymbol);

    ICsFileBuilder EndPartialType(ITypeSymbol typeSymbol);

    string Build();
}
